/** Node tier mapping for App↔Infra view. Higher tier = lower position in the visual hierarchy. */
export const NODE_TIER: Record<string, number> = {
  BusinessApplication: 0,
  BusinessDomain: 0,
  BusinessProcess: 0,
  Application: 1,
  Service: 1,
  API: 2,
  Module: 2,
  Feature: 2,
  Container: 3,
  VM: 3,
  DeploymentEnvironment: 3,
  KubernetesCluster: 3,
  CloudResource: 4,
  Network: 4,
  IAMRole: 4,
  IAMPolicy: 4,
  Database: 5,
  DataFlow: 5,
  SecurityFinding: 5,
  Vulnerability: 5,
}
