import { useEffect, useState } from 'react'
import { Coins } from 'lucide-react'
import { qaApi } from '../../api/qa'
import type { QaRunCost } from '../../api/qa'

/**
 * What a run spent on model calls.
 *
 * Today that is nothing, and saying so in words is the whole point of this component.
 * A run's test plan is derived from the knowledge graph rather than generated by a
 * model — a deliberate choice, because a generated plan is neither reproducible nor
 * free — and execution is Playwright, HTTP and file checks. So there is no spend to
 * report, and rendering "$0.00" would claim a measurement that was never taken. "No
 * model calls" and "zero dollars of measured spend" are different statements and only
 * one of them is true.
 *
 * It is wired anyway, because `exploratory` is already carried end to end on the run
 * row and the first thing it will do when implemented is call a model. Attribution
 * built afterwards never catches the spend that happened in between.
 */
export default function RunCost({ projectId, runId }: {
  projectId: string
  runId: string
}) {
  const [cost, setCost] = useState<QaRunCost | null>(null)
  const [unavailable, setUnavailable] = useState('')

  useEffect(() => {
    let stop = false
    qaApi.runCost(runId, projectId)
      .then(({ data }) => { if (!stop) setCost(data) })
      .catch((e: any) => {
        if (stop) return
        // 503 means the usage index is missing in this deployment. That is an absence
        // of evidence, not evidence of zero, and must not render as "no calls".
        setUnavailable(e?.response?.status === 503
          ? (e?.response?.data?.detail || 'Usage history cannot be read here.')
          : 'Could not read this run’s usage.')
      })
    return () => { stop = true }
  }, [projectId, runId])

  if (unavailable) {
    return <p style={{ ...muted, color: '#f59e0b' }}>{unavailable}</p>
  }
  if (!cost) return <p style={muted}>Loading…</p>

  if (!cost.calls) {
    return (
      <p style={{ ...muted, lineHeight: 1.7 }}>
        This run made no model calls. QualityMind derives its test plan from the
        knowledge graph rather than generating it, so running tests costs no tokens.
      </p>
    )
  }

  return (
    <div style={{ display: 'grid', gap: 10 }}>
      <div style={{ display: 'flex', gap: 22, flexWrap: 'wrap',
                    fontVariantNumeric: 'tabular-nums' }}>
        <Figure label="cost" value={`$${cost.costUsd.toFixed(4)}`} accent />
        <Figure label="calls" value={String(cost.calls)} />
        <Figure label="input" value={fmt(cost.inputTokens)} />
        <Figure label="output" value={fmt(cost.outputTokens)} />
        {cost.cacheReadTokens > 0 && (
          <Figure label="cache read" value={fmt(cost.cacheReadTokens)} />
        )}
        {cost.cacheCreationTokens > 0 && (
          <Figure label="cache write" value={fmt(cost.cacheCreationTokens)} />
        )}
      </div>

      {cost.byModel.length > 1 && (
        <div style={{ display: 'grid', gap: 4 }}>
          {cost.byModel.map(m => (
            <div key={m.model} style={{ display: 'flex', alignItems: 'center', gap: 10,
                                        fontSize: 11.5,
                                        fontVariantNumeric: 'tabular-nums' }}>
              <Coins size={11} style={{ color: 'var(--color-muted)', flexShrink: 0 }} />
              <span style={{ fontFamily: 'var(--font-mono)' }}>{m.model}</span>
              <span style={{ color: 'var(--color-muted)' }}>
                {m.calls} call{m.calls === 1 ? '' : 's'}
              </span>
              <span style={{ marginLeft: 'auto' }}>${m.cost.toFixed(4)}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function Figure({ label, value, accent = false }: {
  label: string; value: string; accent?: boolean
}) {
  return (
    <div>
      <div style={{ fontSize: 16, fontWeight: 700,
                    color: accent ? 'var(--color-primary)' : 'var(--color-text)' }}>
        {value}
      </div>
      <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: '.06em',
                    color: 'var(--color-text-secondary)' }}>{label}</div>
    </div>
  )
}

/** Thousands separators only — a token count is read, not computed from. */
function fmt(n: number): string {
  return n.toLocaleString()
}

const muted: React.CSSProperties = {
  fontSize: 12, color: 'var(--color-text-secondary)', margin: 0,
}
